version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql  
    networks:
      - twotier
 

  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops
    depends_on:
      - mysql
    networks:
      - twotier
    restart: always


  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"  
    environment:
      MYSQL_HOST: mysql  
      MYSQL_USER: root  
      MYSQL_PASSWORD: root  
      MYSQL_DB: devops  
    depends_on:
      - mysql  
    networks:
      - twotier


networks:
  twotier:
  
volumes:
  mysql_data:
    driver: local 