version: '3.8'

services:
  
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"  
    environment:
      MYSQL_HOST: mysql  
      MYSQL_USER: root  
      MYSQL_PASSWORD: root  
      MYSQL_DB: devops  
    depends_on:
      - mysql  

 
  mysql:
    image: mysql:5.7  
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: devops  
    ports:
      - "3306:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data:
    driver: local 
